# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/main/nixos/.sops.yaml
# for a more complex example.
keys:
  - &admin_lillian age12e00qvf4shtmsfq3ujamyaa72pjvad2qhrxkvpl9hryrjvgxev4sjhmkxz
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_lillian
#Run the following command to create EDI-Lillian.yaml in the secrets folder:
# nix-shell -p sops --run "sops secrets/EDI-Lillian.yaml"